info:
  contact:
    name: EWC 
    url: https://eudiwalletconsortium.org/
  description:
    The EWC APIs are defined to be used across all wallet providers within EWC according the [EWC RFCs](https://github.com/EWC-consortium/eudi-wallet-rfcs). 
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  title: EWC APIs
  version: 2024.03.1
openapi: 3.1.0
